FORMAT: 1A
HOST: http://fortunecookieapi.herokuapp.com

# Fortune Cookie API
Fortune Cookie API retrieves data to create a fortune cookie - fortunes, lotto numbers, and a brief lesson in Simplified Chinese.

# Group Notes
Notes related resources of the **Fortune Cookie API**

## Fortunes Collection [/v1/fortunes{?limit,skip,page}]
### List all Fortunes [GET]

+ Parameters
    + limit (integer,optional) ... Quantity of fortunes to return, default 100, max 1000
    + skip (integer,optional) ... Fortunes to skip before fetching, default 0
    + page (integer,optional) ... Page number taking into account given limit, default 1
    
+ Response 200 (application/json)

        [{
          "id": "53ffcf1d4ea4f76d1b8f223e", "message": "This fortune intentionally left blank"
        }, {
          "id": "53ffcf1d4ea4f76d1b8f223f", "message": "Tomorrow is a latter-day"
        }]

## Fortune [/v1/fortunes/{id}]
A single Fortune object with all its details

+ Parameters
    + id (required, number, `1`) ... `id` of the Fortune to perform action with. Has example value.

### Retrieve a Fortune [GET]
+ Response 200 (application/json)

    + Body

            { "id": "53ffcf1d4ea4f76d1b8f223f", "message": "This fortune intentionally left blank" }

## Lottos Collection [/v1/lottos{?limit,skip,page,firstId}]
### List all Lottos [GET]

+ Parameters
    + limit (integer,optional) ... Quantity of lotto numbers to return, default 100, max 1000
    + skip (integer, optional) ... Fortunes to skip before fetching, default 0
    + page (integer,optional) ... Page number taking into account given limit, default 1
    + firstId (string,optional) ... Initial lotto to fetch, default "000000000000000000000000"

+ Response 200 (application/json)

        [{
          "id": "001000200030004000500006", "numbers": [10,20,30,40,50,6]
        }, {
          "id": "001500240011000900100055", "numbers": [15,24,11,9,10,55]
        }]

## Lotto [/v1/lottos/{id}]
A single Lotto object with all its details

+ Parameters
    + id (required, number, `1`) ... `id` of the Lotto to perform action with. Has example value.

### Retrieve a Lotto [GET]
+ Response 200 (application/json)

    + Body

            { "id": "001000200030004000500006", "numbers": [10,20,30,40,50,6] }

## Lessons Collection [/v1/lessons{?limit,skip,page}]
### List all Lessons [GET]

+ Parameters
    + limit (integer,optional) ... Quantity of lessons to return, default 100, max 1000
    + skip (integer, optional) ... Fortunes to skip before fetching, default 0
    + page (integer,optional) ... Page number taking into account given limit, default 1
    
+ Response 200 (application/json)

        [{
          "id": "53ffcf1d4ea4f76d1b8f223e", "chinese": "因特网", "romanization": "yintewang", "english": "internet"
        }, {
          "id": "53ffcf1d4ea4f76d1b8f223f", "chinese": "狮子狗", "romanization": "shizi gou", "english": "poodle"
        }]

## Lesson [/v1/lessons/{id}]
A single Lesson object with all its details

+ Parameters
    + id (required, number, `1`) ... `id` of the Lesson to perform action with. Has example value.

### Retrieve a Lesson [GET]
+ Response 200 (application/json)

    + Body

            { "id": "53ffcf1d4ea4f76d1b8f223f", "chinese": "因特网", "romanization": "yintewang", "english": "internet" }

## Cookie [/v1/cookie{?fortuneId,lottoId,lessonId,limit}]
### Returns whole cookies, which includes a fortune, lotto, and lesson [GET]

+ Parameters
    + fortuneId (string,optional) ... ID of the Fortune to build the cookie (random if not specified).
    + lottoId (string,optional) ... ID of the Lotto to build the cookie (random if not specified).
    + lessonId (string,optional) ... ID of the Lesson to build the cookie (random if not specified).
    + limit (integer,optional) ... number of cookies to fetch, default 1, max 1000

+ Response 200 (application/json)

    + Body

            {
                "fortune":
                    { "id": "53ffcf1d4ea4f76d1b8f223e", "message": "This fortune intentionally left blank" },
                "lotto":
                    { "id": "001000200030004000500006", "numbers": [10,20,30,40,50,6] },
                "lesson":
                    { "id": "53ffcf1d4ea4f76d1b8f2241", "chinese": "因特网", "romanization": "yintewang", "english": "internet" }
            }